apiVersion: v1
kind: Pod
metadata:
  name: oneit-testpod
spec:
  containers:
    - name: test-container
      image: cinderstries/oneit-sample
      env:
        # Define the environment variable
        - name: OPCUA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: oneit-cm
              # Specify the key associated with the value
              key: conf
  restartPolicy: Never